services:
  cms-client-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-client-appv2
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://cms-app-backend-k09y.onrender.com}
    restart: unless-stopped